# Deploy to Amazon EC2
name: cd

on:
  pull_request:
    branches:
      - master
env:
  DOCKER_IMAGE: ghcr.io/parksujeong74/cicd
  VERSION: latest

jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    # build
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
    # docker build start
    - name: Set up docker buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    # Caching
    - name: Cache docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ env.VERSION }}
        restore-keys: |
          ${{ runner.os }}-buildx-
          
    # github container registry login
    - name: Login to ghcr
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
          
    # docker push
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        file: ./docker
        builder: ${{ steps.buildx.outputs.name }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ env.DOCKER_IMAGE }}:${{ env.VERSION }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
        
    - name: Force new deploy EC2 service
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      working-directory: ${{ env.working-directory }}
      run: aws ecs update-service --cluster main --service api-server --force-new-deployment
